### ISSUE TITLE
Howto install on ESPHome? 

### ISSUE THREAD

**Issue by fpibbs** [TillFleisch/ESPHome-HLK-LD2450#27]
Could seem a dumb question, but I face many problems integrating this feature on the esphome in home assistant.
Could you please briefly describe?

Thanks

**Comment by TillFleisch** [comment]
I would first recommended getting familiar with ESPHome and how you can integrate ESPHome device into Home Assistant.
[Here is the official guide](https://esphome.io/guides/getting_started_hassio), which you can use to get an ESP up and running with Home Assistant.

Once you've done that you can add this repository as a custom component using:

```yaml
external_components:
  - source: github://TillFleisch/ESPHome-HLK-LD2450@main
```

Wire up the sensor to the ESP while making sure that the EPSs RX pin is connected to the LD2450s TX pin and vice versa for the other UART line(ground to ground, 5V to 5V). Add a UART configuration to your yaml config like this and make sure you are using the correct pins for your ESP:

```yaml
uart:
  id: uart_bus
  rx_pin: 
    number: GPIO16
    mode:
      input: true
      pullup: true
  tx_pin: 
    number: GPIO17
    mode:
      input: true
      pullup: true
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  data_bits: 8
```

Then you can proceed to add a configuration for the LD2450 sensor. The following basics config was stolen form the [basic example](https://github.com/TillFleisch/ESPHome-HLK-LD2450/blob/main/examples%2Fbasic.yaml):

```yaml
LD2450:
  uart_id: uart_bus
  max_detection_distance:
    name: "Max Distance"
    initial_value: 4m
  #max_detection_distance: 1.5m
  occupancy:
    name: Occupancy
```

This should provide you with a single binary sensor which activates if movement is detected within the sensors field of view (limited to 4m distance).
(Make sure to update the ESPs firmware, for instance using the OTA-update functionality.)

Once you've got this running, you can proceed to build a more complicated configuration based on the documentation provided within this repository.
