### ISSUE TITLE
Sensor unreliable when using long wires

### ISSUE THREAD

**Issue by Aaroneisele55** [TillFleisch/ESPHome-HLK-LD2450#9]
Hello,
I have two LD2450 Sensors on the same ESP32 board.
Both detect presence well, but one of them (S2 or ld2450_external in the config) doesn't allow me to switch on the Bluetooth or the Multi-Target mode. 
When I flip the switch to ON, it resets to OFF after approximately 2 seconds. 
Power cycling the sensor and/or ESP32 doesn't help.
It could be a similar problem to this Issue: https://github.com/TillFleisch/ESPHome-HLK-LD2450/issues/5

I also get this message in the logs after startup:

```
[14:52:31][W][LD2450:119]: Entering config mode failed, clearing command queue.
[14:52:31][W][LD2450:126]: Sending command timed out! Is the sensor connected?
[14:52:33][D][LD2450:271]: Clearing RX buffer.
```

Here's my config:

```
esphome:
  name: mmwavetest-d1mini32-02
  friendly_name: mmwavetest_d1mini32-02

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  logs:
    sensor: ERROR
    binary_sensor: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "8a/INyAsUXFGEf/4HuU2oXGTLKI0m+ddBEOYJbH4Cqw="

ota:
  password: "bf09a8dda9090dbe7040bed6da345672"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Mmwavetest-D1Mini32-02"
    password: "xxeHosZcLSnu"

captive_portal:

#begin customisation (non-default things)
external_components:
  - source: github://TillFleisch/ESPHome-HLK-LD2450@main
    refresh: always

uart:
  - id: uart_bus_internal
    rx_pin: GPIO19
    tx_pin: GPIO18
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
    data_bits: 8
    rx_buffer_size: 1024
  - id: uart_bus_external
    rx_pin: GPIO21 
    tx_pin:  GPIO22
    baud_rate: 256000
    parity: NONE
    stop_bits: 1
    rx_buffer_size: 1024
LD2450:
  - id: ld2410_internal
    uart_id: uart_bus_internal
    targets:
      - target:
          name: "S1 T1"
          x_position:
            id: t1_xpos_s1
          y_position:
            id: t1_ypos_s1
          distance: 
            id: t1_dist_s1
      - target:
          name: "S1 T2"
          x_position:
            id: t2_xpos_s1
          y_position:
            id: t2_ypos_s1
          distance: 
            id: t2_dist_s1
      - target:
          name: "S1 T3"
          x_position:
            id: t3_xpos_s1
          y_position:
            id: t3_ypos_s1
          distance: 
            id: t3_dist_s1
    flip_x_axis: false
    fast_off_detection: false
    max_detection_distance:
      name: "Max Distance S1"
      initial_value: "6m"
    restart_button:
      name: "Restart Sensor S1"
    tracking_mode_switch:
      name: "Multiple Target Tracking S1"
      restore_mode: ALWAYS_ON
    bluetooth_switch:
      name: "Sensor Bluetooth S1"
      restore_mode: ALWAYS_ON
    occupancy:
      name: "Occupancy S1"
      id: occupancy_s1
    target_count:
      name: "Target Count S1"
    zones:
      - zone:
          name: "Tür aussen"
          margin: 10cm
          target_timeout: 0s
          polygon:
            - point: 
                x: 1.42m
                y: 3m
            - point:
                x: 0.66m
                y: 3m
            - point:
                x: 0.66m
                y: 3.2m
            - point: 
                x: 1.42m
                y: 3.2m
            

          occupancy:
            id: tuer_aussen
            name: Occupancy Tür aussen
      - zone:
          name: "Tür innen"
          margin: 10cm
          target_timeout: 0s
          polygon:
            - point:
                x: 0.6m
                y: 2.6m
            - point:
                x: 0.66m
                y: 3.1m
            - point:
                x: 1.42m
                y: 3.1m
            - point:
                x: 1.42m
                y: 2.6m
          occupancy:
            id: tuer_innen
            name: Occupancy Tür innen
  - id: ld2410_external
    uart_id: uart_bus_external
    targets:
      - target:
          name: "S2 T1"
          x_position:
            id: t1_xpos_s2
          y_position:
            id: t1_ypos_s2
          distance: 
            id: t1_dist_s2
      - target:
          name: "S2 T2"
          x_position:
            id: t2_xpos_s2
          y_position:
            id: t2_ypos_s2
          distance: 
            id: t2_dist_s2
      - target:
          name: "S2 T3"
          x_position:
            id: t3_xpos_s2
          y_position:
            id: t3_ypos_s2
          distance: 
            id: t3_dist_s2
    flip_x_axis: false
    fast_off_detection: false
    max_detection_distance:
      name: "Max Distance S2"
      initial_value: "6m"
    restart_button:
      name: "Restart Sensor S2"
    tracking_mode_switch:
      name: "Multiple Target Tracking S2"
      restore_mode: ALWAYS_ON
    bluetooth_switch:
      name: "Sensor Bluetooth S2"
      restore_mode: ALWAYS_ON
    occupancy:
      id: occupancy_s2
      name: "Occupancy S2"
    target_count:
      name: "Target Count S2"
binary_sensor:
    - id: occupancy_combined
      platform: template
      name: "Occupancy combined"
      lambda: |-
        return (id(occupancy_s1).state || id(occupancy_s2).state);
      filters:
        - delayed_off: 10s
    - name: Tuer innen korrigiert
      platform: template
      lambda: |-
        return (id(tuer_innen).state);
      filters:
        - delayed_off: 2s
    - name: Tuer aussen korrigiert
      platform: template
      lambda: |-
        return (id(tuer_aussen).state);
      filters:
        - delayed_off: 2s


button:
  - platform: restart
    name: Restart

```
How could I fix this issue?

Best regards 
Aaron Eisele
